apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xxxxxxxxx
    # service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
spec:
  selector:
    name: app
  type: LoadBalancer
  ports:
   -  name: http
      protocol: TCP
      port: 80
      targetPort: 80